/**
 * TypeScript type definitions for xcsift output.
 * These types match the JSON output from the xcsift CLI tool.
 * 
 * xcsift parses xcodebuild/swift build output and returns structured JSON
 * containing errors, warnings, test failures, coverage data, and more.
 */

// === Core Result Types ===

export interface XcsiftResult {
    status: 'success' | 'failed';
    summary: XcsiftSummary;
    errors?: XcsiftError[];
    warnings?: XcsiftWarning[];
    failed_tests?: XcsiftTestFailure[];
    linker_errors?: XcsiftLinkerError[];
    slow_tests?: XcsiftSlowTest[];
    coverage?: XcsiftCoverage;
    build_info?: XcsiftBuildInfo;
    executables?: string[];
}

export interface XcsiftSummary {
    errors: number;
    warnings: number;
    failed_tests: number;
    passed_tests?: number;
    linker_errors: number;
    test_time?: string;
    build_time?: string;
}

// === Error Types ===

export interface XcsiftError {
    file: string;
    line: number;
    column?: number;
    message: string;
}

export interface XcsiftWarning {
    file: string;
    line: number;
    column?: number;
    message: string;
    type?: 'deprecation' | 'unused' | 'concurrency' | 'other';
}

export interface XcsiftLinkerError {
    symbol?: string;
    message: string;
    file?: string;
}

// === Test Types ===

export interface XcsiftTestFailure {
    test: string;
    file: string;
    line: number;
    message: string;
}

export interface XcsiftSlowTest {
    test: string;
    duration: number;
    threshold: number;
}

// === Coverage Types ===

export interface XcsiftCoverage {
    line_coverage: number;
    function_coverage?: number;
    branch_coverage?: number;
    files?: XcsiftFileCoverage[];
}

export interface XcsiftFileCoverage {
    path: string;
    line_coverage: number;
    covered_lines: number;
    total_lines: number;
    functions?: XcsiftFunctionCoverage[];
}

export interface XcsiftFunctionCoverage {
    name: string;
    line: number;
    execution_count: number;
}

// === Build Info Types ===

export interface XcsiftBuildInfo {
    targets: XcsiftTargetInfo[];
    total_time?: string;
}

export interface XcsiftTargetInfo {
    name: string;
    phases: XcsiftPhase[];
    duration?: string;
}

export interface XcsiftPhase {
    name: string;
    duration: string;
    files?: number;
}

// === Parser Configuration ===

export interface XcsiftParseOptions {
    /** Include detailed warnings list (default: false, only shows count) */
    includeWarnings?: boolean;
    /** Include code coverage data if available */
    includeCoverage?: boolean;
    /** Include coverage details per-file (requires includeCoverage) */
    includeCoverageDetails?: boolean;
    /** Include per-target build phases and timing */
    includeBuildInfo?: boolean;
    /** Include executable targets generated by the build */
    includeExecutables?: boolean;
    /** Threshold in seconds for slow test detection */
    slowThreshold?: number;
    /** Output format (json is default, toon uses fewer tokens) */
    format?: 'json' | 'toon';
    /** Treat warnings as errors */
    warningsAsErrors?: boolean;
    /** Suppress output when build succeeds with no issues */
    quiet?: boolean;
    /** Path to coverage data (auto-detected if not specified) */
    coveragePath?: string;
}

/** Parser mode - which backend to use */
export type XcsiftMode = 'cli' | 'mcp' | 'auto';

// === Configuration ===

export interface XcsiftConfig {
    /** Whether xcsift integration is enabled */
    enabled: boolean;
    /** Parser mode: 'cli' uses xcsift binary, 'mcp' uses xcsift-mcp server, 'auto' tries both */
    mode: XcsiftMode;
    /** Slow test threshold in seconds */
    slowThreshold: number;
    /** Include warnings in output */
    includeWarnings: boolean;
    /** Include build timing info */
    includeBuildInfo: boolean;
    /** Command to run xcsift MCP server (default: 'xcsift-mcp') */
    mcpCommand?: string;
    /** Arguments for xcsift MCP server */
    mcpArgs?: string[];
}

/** Default xcsift configuration */
export const DEFAULT_XCSIFT_CONFIG: XcsiftConfig = {
    enabled: true,
    mode: 'auto',
    slowThreshold: 1.0,
    includeWarnings: true,
    includeBuildInfo: false,
    mcpCommand: 'xcsift-mcp',
    mcpArgs: []
};
